# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys


class Ui_MainWindow(object):
#     def __init__(self) -> None:
#         import sys
#         app = QtWidgets.QApplication(sys.argv)
#         MainWindow = QtWidgets.QMainWindow()
#         self.setupUi(MainWindow)
#         MainWindow.show()
#         sys.exit(app.exec_())

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 340)
        MainWindow.setMinimumSize(QtCore.QSize(490, 340))
        MainWindow.setMaximumSize(QtCore.QSize(490, 340))
        MainWindow.setStyleSheet("background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UpFrame = QtWidgets.QFrame(self.centralwidget)
        self.UpFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UpFrame.setObjectName("UpFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.UpFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ControlFrame = QtWidgets.QFrame(self.UpFrame)
        self.ControlFrame.setMaximumSize(QtCore.QSize(470, 300))
        self.ControlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ControlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ControlFrame.setObjectName("ControlFrame")
        self.label = QtWidgets.QLabel(self.ControlFrame)
        self.label.setGeometry(QtCore.QRect(70, 45, 80, 40))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(200, 200, 200);")
        self.label.setObjectName("label")
        self.error_label = QtWidgets.QLabel(self.ControlFrame)
        self.error_label.setGeometry(QtCore.QRect(154, 92, 200, 21))
        self.error_label.setStyleSheet("color: rgb(200, 200, 200);\n"
"padding: 5px;")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.input_comboBox = QtWidgets.QComboBox(self.ControlFrame)
        self.input_comboBox.setGeometry(QtCore.QRect(154, 45, 200, 45))
        self.input_comboBox.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.input_comboBox.setFont(font)
        self.input_comboBox.setStyleSheet("QComboBox{\n"
"    background-color: rgb(45, 45, 45);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 10px;\n"
"    color: rgb(135, 135, 135);\n"
"    padding: 5px\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(65, 65, 65);\n"
"    border: 2px solid rgb(85, 85, 85);\n"
"    color: rgb(135, 135, 135);\n"
"}\n"
"\n"
"QComboBox:focus{\n"
"    background-color: rgb(85, 85, 85);\n"
"    border: 2px solid rgb(255, 255, 0);\n"
"    color: rgb(135, 135, 135);\n"
"}")
        self.input_comboBox.setEditable(True)
        self.input_comboBox.setObjectName("input_comboBox")
        self.input_comboBox.addItem("")
        self.input_comboBox.addItem("")
        self.input_comboBox.addItem("")
        self.input_comboBox.addItem("")
        self.input_comboBox.addItem("")
        self.input_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.ControlFrame)
        self.verticalLayout.addWidget(self.UpFrame)
        self.DownFrame = QtWidgets.QFrame(self.centralwidget)
        self.DownFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DownFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DownFrame.setObjectName("DownFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.DownFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttons_frame = QtWidgets.QFrame(self.DownFrame)
        self.buttons_frame.setMaximumSize(QtCore.QSize(470, 300))
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.sleep_pushButton = QtWidgets.QPushButton(self.buttons_frame)
        self.sleep_pushButton.setGeometry(QtCore.QRect(252, 90, 90, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sleep_pushButton.setFont(font)
        self.sleep_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(135, 135, 135);\n"
"    color: rgb(35, 35, 35);\n"
"    border-radius: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:focus{\n"
"    color: rgb(233, 241, 0);\n"
"}")
        self.sleep_pushButton.setObjectName("sleep_pushButton")
        self.cancel_pushButton_2 = QtWidgets.QPushButton(self.buttons_frame)
        self.cancel_pushButton_2.setGeometry(QtCore.QRect(147, 90, 90, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_pushButton_2.setFont(font)
        self.cancel_pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(135, 135, 135);\n"
"    color: rgb(35, 35, 35);\n"
"    border-radius: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton:focus{\n"
"    color: rgb(233, 241, 0);\n"
"}")
        self.cancel_pushButton_2.setObjectName("cancel_pushButton_2")
        self.horizontalLayout_2.addWidget(self.buttons_frame)
        self.verticalLayout.addWidget(self.DownFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.sleep_pushButton.clicked.connect(self.onSleepClick)
        self.cancel_pushButton_2.clicked.connect(self.onCancelClick)

    def onSleepClick(self):
        strTime = self.input_comboBox.currentText()
        l = strTime.split(' ')
        if len(l) == 2:
                time = int(l[0]) * 60
        elif len(l) == 3:
                time = int(l[0]) * 3600 + int(l[2]) * 60
        os.system("shutdown /s /t " + str(time))

    def onCancelClick(self):
        os.system("shutdown /a")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Time:"))
        self.input_comboBox.setCurrentText(_translate("MainWindow", "30 min"))
        self.input_comboBox.setItemText(0, _translate("MainWindow", "30 min"))
        self.input_comboBox.setItemText(1, _translate("MainWindow", "1 h 00"))
        self.input_comboBox.setItemText(2, _translate("MainWindow", "1 h 30"))
        self.input_comboBox.setItemText(3, _translate("MainWindow", "2 h 00"))
        self.input_comboBox.setItemText(4, _translate("MainWindow", "2 h 30"))
        self.input_comboBox.setItemText(5, _translate("MainWindow", "3 h 00"))
        self.sleep_pushButton.setText(_translate("MainWindow", "Sleep"))
        self.cancel_pushButton_2.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
